sudo: required
language: python
env:
  matrix:
    - SLURM=17.02.7 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.6 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.5 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.4 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.3 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.2 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.1 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.7 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.6 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.5 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.4 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.3 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.2 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.1 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.7 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.6 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.5 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.4 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.3 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.2 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.1 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.7 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.6 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.5 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.4 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.3 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.2 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.1 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.7 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.6 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.5 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.4 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.3 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.2 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.1 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.7 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.6 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.5 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.4 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.3 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.2 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.1 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.7 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.6 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.5 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.4 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.3 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.2 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.1 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.7 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.6 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.5 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.4 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.3 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.2 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.1 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
services:
  - docker
before_install:
  - docker pull giovtorres/docker-centos$CENTOS-slurm:$SLURM
install: true
before_script:
  - docker run -d -it -h ernie --name slurm-$SLURM giovtorres/docker-centos$CENTOS-slurm:$SLURM
  - docker exec slurm-$SLURM git clone --branch=$TRAVIS_BRANCH https://github.com/PySlurm/pyslurm.git
  - docker exec -e PYTHON=$PYTHON -e CYTHON=$CYTHON slurm-$SLURM /pyslurm/scripts/build.sh
  - docker exec slurm-$SLURM /pyslurm/scripts/config.sh
  - docker exec -e PYTHON=$PYTHON slurm-$SLURM /pyslurm/scripts/debug.sh
script:
  - docker exec -e PYTHON=$PYTHON slurm-$SLURM /pyslurm/scripts/run_tests.sh
