sudo: required
language: python
env:
  matrix:
    - SLURM_VERSION=17.02.6 CYTHON_VERSION=0.24 VER="7"
    - SLURM_VERSION=17.02.5 CYTHON_VERSION=0.24 VER="7"
    - SLURM_VERSION=17.02.4 CYTHON_VERSION=0.24 VER="7"
    - SLURM_VERSION=17.02.3 CYTHON_VERSION=0.24 VER="7"
    - SLURM_VERSION=17.02.2 CYTHON_VERSION=0.24 VER="7"
    - SLURM_VERSION=17.02.1 CYTHON_VERSION=0.24 VER="7"
    - SLURM_VERSION=17.02.6 CYTHON_VERSION=0.24 VER="6"
    - SLURM_VERSION=17.02.5 CYTHON_VERSION=0.24 VER="6"
    - SLURM_VERSION=17.02.4 CYTHON_VERSION=0.24 VER="6"
    - SLURM_VERSION=17.02.3 CYTHON_VERSION=0.24 VER="6"
    - SLURM_VERSION=17.02.2 CYTHON_VERSION=0.24 VER="6"
    - SLURM_VERSION=17.02.1 CYTHON_VERSION=0.24 VER="6"
    - SLURM_VERSION=17.02.6 CYTHON_VERSION=0.19.2 VER="7"
    - SLURM_VERSION=17.02.5 CYTHON_VERSION=0.19.2 VER="7"
    - SLURM_VERSION=17.02.4 CYTHON_VERSION=0.19.2 VER="7"
    - SLURM_VERSION=17.02.3 CYTHON_VERSION=0.19.2 VER="7"
    - SLURM_VERSION=17.02.2 CYTHON_VERSION=0.19.2 VER="7"
    - SLURM_VERSION=17.02.1 CYTHON_VERSION=0.19.2 VER="7"
    - SLURM_VERSION=17.02.6 CYTHON_VERSION=0.19.2 VER="6"
    - SLURM_VERSION=17.02.5 CYTHON_VERSION=0.19.2 VER="6"
    - SLURM_VERSION=17.02.4 CYTHON_VERSION=0.19.2 VER="6"
    - SLURM_VERSION=17.02.3 CYTHON_VERSION=0.19.2 VER="6"
    - SLURM_VERSION=17.02.2 CYTHON_VERSION=0.19.2 VER="6"
    - SLURM_VERSION=17.02.1 CYTHON_VERSION=0.19.2 VER="6"
services:
  - docker
before_install:
  - docker pull giovtorres/docker-centos7-slurm:$SLURM_VERSION
install: true
before_script:
  - docker run -d -it -h ernie --name slurm-$SLURM_VERSION giovtorres/docker-centos$VER-slurm:$SLURM_VERSION
  - docker exec slurm-$SLURM_VERSION bash -c "pip install Cython==$CYTHON_VERSION"
  - docker exec slurm-$SLURM_VERSION git clone https://github.com/PySlurm/pyslurm.git
  - docker exec slurm-$SLURM_VERSION bash -c "cd pyslurm && python setup.py build"
  - docker exec slurm-$SLURM_VERSION bash -c "cd pyslurm && python setup.py install"
script:
  - docker exec slurm-$SLURM_VERSION python -c "import pyslurm; print pyslurm.version()"
