sudo: required
language: python
env:
  matrix:
    - SLURM=17.02.6 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.5 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.4 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.3 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.2 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.1 CYTHON=0.25.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.6 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.5 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.4 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.3 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.2 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.1 CYTHON=0.25.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.6 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.5 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.4 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.3 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.2 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.1 CYTHON=0.25.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.6 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.5 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.4 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.3 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.2 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.1 CYTHON=0.19.2 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.6 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.5 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.4 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.3 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.2 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.1 CYTHON=0.19.2 CENTOS=7 PYTHON=3.4
    - SLURM=17.02.6 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.5 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.4 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.3 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.2 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.1 CYTHON=0.19.2 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.6 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.5 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.4 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.3 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.2 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.1 CYTHON=0.15.1 CENTOS=7 PYTHON=2.7
    - SLURM=17.02.6 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.5 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.4 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.3 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.2 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
    - SLURM=17.02.1 CYTHON=0.15.1 CENTOS=6 PYTHON=2.6
services:
  - docker
before_install:
  - docker pull giovtorres/docker-centos$CENTOS-slurm:$SLURM
install: true
before_script:
  - docker run -d -it -h ernie --name slurm-$SLURM giovtorres/docker-centos$CENTOS-slurm:$SLURM
  - if [ $CENTOS -eq 7 ]; then docker exec slurm-$SLURM bash -c "yum makecache fast && yum -y install python34{,-devel,-pip}"; fi
  - docker exec slurm-$SLURM pip$PYTHON install nose Cython==$CYTHON
  - docker exec slurm-$SLURM git clone --branch=$TRAVIS_BRANCH https://github.com/PySlurm/pyslurm.git
  - docker exec slurm-$SLURM bash -c "cd pyslurm && python$PYTHON setup.py build"
  - docker exec slurm-$SLURM bash -c "cd pyslurm && python$PYTHON setup.py install"
script:
  - docker exec slurm-$SLURM python$PYTHON -c "import pyslurm; print(pyslurm.version())"
  - docker exec slurm-$SLURM python$PYTHON -c "import pyslurm; print(pyslurm.slurm_api_version())"
  - docker exec slurm-$SLURM sbatch --wrap="sleep 1000"
  - docker exec slurm-$SLURM nosetests-$PYTHON -v /pyslurm/tests
